var five = 5;
var ten = 10;
console.log(" Test 1 : five is equal to 5?");
console.log(five == 5);
console.log("\n Test 2 : ten is equal to 10?");
console.log(ten == 10);
console.log("\n Test 3 : five is not equal to 10?");
console.log(five != ten);
console.log("\n Test 4 : 10 is greater than 5?");
console.log(ten > 5);
console.log("\n Test 5 : 5 is lesser than 10?");
console.log(five < ten);
console.log(" Test 6 : five is  not equal to 5?");
console.log(5 != 5);
console.log("\n Test 7 : ten is not  equal to 10?");
console.log(ten != 10);
console.log("\n Test 8 : five is  equal to 10?");
console.log(five == ten);
console.log("\n Test 9 : 10 is lesser than 5?");
console.log(ten < 5);
console.log("\n Test 10 : 5 is greater than 10?");
console.log(five > ten);
